#strings are immutible
a="tushar++ ++ +"
print(len(a))
print(a.upper())
b="i am good boy"
c=(b.upper())
print(c)
print(c.lower())
print(a.rstrip("+"))
print(a.replace("tushar","shantanu"))
print(a.split(" "))
print(a.capitalize())
d="You are gooOd girl"
print(d.capitalize())
print(d.center(50))
print(d.count("o"))
print(d.endswith("!!"))
print(d.find("are"))
print(d.index("are"))
print(d.isalnum())
print(d.isalpha())
print(d.islower())
print(d.isupper())
s=(d.upper())
print(s)
print(s.isupper())
print(s.isprintable())
print(s.isspace())
print(d.swapcase())

